export const SET_LOCATION = 'SET_LOCATION';
export const CURRENT_WEATHER = 'CURRENT_WEATHER';
export const FIVE_DAYS_FORECASTS = 'FIVE_DAYS_FORECASTS';

export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const REMOVE_FROM_FAVORITE = 'REMOVE_FROM_FAVORITE';
export const FAVORITE_CITY = 'FAVORITE_CITY';
export const CHECK_IF_EXISTS_IN_FAVORITES = 'CHECK_IF_EXISTS_IN_FAVORITES';

export const DARK_MODE = 'DARK_MODE';
export const SEARCH_LOCATION = 'SEARCH_LOCATION';
export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export const IS_LOADING = 'IS_LOADING';
export const CONVERT_TEMP_UNITS = 'CONVERT_TEMP_UNITS';
export const REDIRECT = 'REDIRECT';
export const SLIDE_MENU = 'SLIDE_MENU';
export const ID_NOT_FOUND = 'ID_NOT_FOUND';
